Уточнение поведения, когда удаление задания может оставить игру без заданий
Party-Buddy/docs pull request #1
Opened 2023-10-30 18:30 UTC by slowlime

Насколько я понимаю, удаление публичного задания удаляет его из всех игр. В таком случае игра может остаться без заданий, что противоречит требованиям. PR уточняет поведение при такой ситуации.

Альтернативное решение: блокировать удаление публичного задания, если оно используется в публичной игре.

2023-10-31 13:49 UTC, AleksandrMatsko requested changes

2023-10-31 13:49 UTC, AleksandrMatsko commented on api.md
> +Перед удалением сервер проверяет все опубликованные игры, использующие это задание.
Предлагаю использовать альтернативное решение

2023-10-31 13:57 UTC, AleksandrMatsko approved these changes

2023-11-01 05:27 UTC, aiwannafly approved these changes

2023-11-04 10:49 UTC, merged